---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 1.
--- DateTime: 2020/11/18 23:47
---

local Stype = require("Stype")
local Cmd = require("Cmd")
local mysql_game = require("database/mysql_game")
local Respones = require("Respones")
local moba_game_config = require("moba_game_config")

--发放奖励
local function _send_bonues_to_user(uid, bonues_info, ret_handler)
    if bonues_info.bonues_time < Utils.timestamp_today() then
        if bonues_info.bonues_time > Utils.timestamp_yesterday() then
            bonues_info.days = bonues_info.days + 1
        else
            bonues_info.days = 1
        end

        if bonues_info.days > #moba_game_config.login_bonues then
            bonues_info.days = 1
        end

        bonues_info.status = 0
        bonues_info.bonues_time = Utils.timestamp()
        bonues_info.bonues = moba_game_config.login_bonues[bonues_info.days]

        mysql_game.update_login_bonues(uid, bonues_info, function(err, ret)
            if err then
                ret_handler(err, nil)
                return
            end
            
            ret_handler(nil, bonues_info)
        end)
        return
    end
    
    ret_handler(nil, bonues_info)
end

local function check_login_bonues(uid, ret_handler)
    mysql_game.get_bonues_info(uid, function(err, bonues_info)
        if err then
            if ret_handler then
                ret_handler(err, nil)
            end
            return
        end

        if bonues_info == nil then
            mysql_game.insert_bonues_info(uid, function(err, bonues_info)
                if err then
                    if ret_handler then
                        ret_handler(err, nil)
                    end
                    return
                end
                check_login_bonues(uid, ret_handler)
            end)
            return
        end

        _send_bonues_to_user(uid, bonues_info, ret_handler)
    end)
end

local login_bonues = {
    check_login_bonues = check_login_bonues
}

return login_bonues