---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 1.
--- DateTime: 2020/9/20 14:56
---
Logger.init("logger/system_server/", "system_server", true)

require("database/mysql_game")

-- 初始化协议模块
local proto_type = {
    PROTO_JSON = 0,
    PROTO_BUF = 1,
}

ProtoMan.init(proto_type.PROTO_BUF)
if ProtoMan.proto_type() == proto_type.PROTO_BUF then
    local cmd_name_map = require("cmd_name_map")
    if cmd_name_map then
        ProtoMan.register_protobuf_cmd_map(cmd_name_map)
    end
end
--end

--开启网络服务
local game_config = require("game_config")
local Stype = require("Stype")
local servers = game_config.servers
print("Auth Server Start at " .. servers[Stype.System].port)
Netbus.tcp_listen(servers[Stype.System].port)
--end

local system_server = require("system_server/system_service")
local ret = Service.register_service(Stype.System, system_server)
if ret then
    print("register System service:[" .. Stype.System .. "] success!!!")
else
    Logger.error("register System service:[" .. Stype.System .. "] failed!!!")
end