---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 1.
--- DateTime: 2020/9/20 15:03
---

local Stype = require("Stype")
local Cmd = require("Cmd")
local ugame = require("system_server/ugame")

local system_service_handlers = {}
system_service_handlers[Cmd.eGetUgameInfoReq] = ugame.get_ugame_info

--{stype, ctype, utag, body}
local function on_system_recv_cmd(s, msg)
    Logger.error(msg[1], msg[2], msg[3])
    if system_service_handlers[msg[2]] then
        system_service_handlers[msg[2]](s, msg)
    end
end

local function on_system_session_disconnect(s, stype)

end

local system_service = {
    on_session_recv_cmd = on_system_recv_cmd,
    on_session_disconnect = on_system_session_disconnect,
}

return system_service