---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 1.
--- DateTime: 2020/11/16 22:25
---

local Stype = require("Stype")
local Cmd = require("Cmd")
local mysql_game = require("database/mysql_game")
local Respones = require("Respones")
local login_bonues = require("system_server/login_bonues")
local redis_game = require("database/redis_game")
local redis_rank = require("database/redis_rank")

local function get_ugameinfo(s, req)
    local uid = req[3]
    mysql_game.get_ugame_info(uid, function(err, ugame_info)
        if err then
            Logger.error(err)
            local msg = {
                Stype.System, Cmd.eGetUgameInfoRes, uid, {
                    status = Respones.SystemErr
                }
            }
            Session.send_msg(s, msg)
            return
        end

        if ugame_info == nil then
            mysql_game.insert_ugame_info(uid, function(err, ret)
                if err then
                    Logger.error(err)
                    local msg = {
                        Stype.System, Cmd.eGetUgameInfoRes, uid, {
                            status = Respones.SystemErr
                        }
                    }
                    Session.send_msg(s, msg)
                    return
                end
                get_ugameinfo(s, req)
            end)
            return
        end

        if ugame_info.ustatus ~= 0 then
            --账号被查封
            local msg = {
                Stype.System, Cmd.eGetUgameInfoRes, uid, {
                    status = Respones.UserIsFreeze
                }
            }
            Session.send_msg(s, msg)
            return
        end

        --redis_center.set_ugame_info_inredis(ugame_info.uid, ugame_info)
        login_bonues.check_login_bonues(uid, function(err, bonues_info)
            if err then
                Logger.error(err)
                local msg = {
                    Stype.System, Cmd.eGetUgameInfoRes, uid, {
                        status = Respones.SystemErr
                    }
                }
                Session.send_msg(s, msg)
                return
            end
            
            redis_game.set_ugame_info_inredis(uid, ugame_info)
            
            --刷新一下世界排行榜
            
            redis_rank.flush_world_rank_with_uchip_inredis(uid, ugame_info.uchip)
            --end
            
            local msg = {
                Stype.System, Cmd.eGetUgameInfoRes, uid, {
                    status = Respones.OK,
                    uinfo = {
                        uchip = ugame_info.uchip,
                        uchip2 = ugame_info.uchip2,
                        uchip3 = ugame_info.uchip3,
                        uvip = ugame_info.uvip,
                        uvip_endtime = ugame_info.uvip_endtime,
                        udata1 = ugame_info.udata1,
                        udata2 = ugame_info.udata2,
                        udata3 = ugame_info.udata3,
                        uexp = ugame_info.uexp,
                        ustatus = ugame_info.ustatus,
                        
                        bonues_status = bonues_info.status,
                        bonues = bonues_info.bonues,
                        days = bonues_info.days
                    }
                }
            }
            Session.send_msg(s, msg)
        end)
    end)
end

local ugame = {
    get_ugame_info = get_ugameinfo
}

return ugame