---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 1.
--- DateTime: 2020/10/18 21:09
---

local mysql_center = require("database/mysql_auth_center")
local redis_center = require("database/redis_center")
local Respones = require("Respones")
local Stype = require("Stype")
local Cmd = require("Cmd")

--修改用户资料  name，sex，uface等
--{stype, ctype, utag, body}
local function do_edit_profile(s, rec_msg)
    local uid = rec_msg[3];
    local edit_profile_req = rec_msg[4];
    print(edit_profile_req.unick, edit_profile_req.uface, edit_profile_req.usex)
    if (string.len(edit_profile_req.unick) <= 0) or
            (edit_profile_req.uface <= 0 or edit_profile_req.uface > 9) or
            (edit_profile_req.usex ~= 0 and edit_profile_req.usex ~= 1) then
        local msg = { Stype.Auth, Cmd.eEditProfileRes, uid, {
            status = Respones.InvalidParams
        } }
        Session.send_msg(s, msg)
        return
    end

    --更新用户中心数据库
    local ret_handle = function(err, res)
        print(uid)
        local ret_status = Respones.OK
        if err then
            ret_status = Respones.SystemErr
        end
        local msg = { Stype.Auth, Cmd.eEditProfileRes, uid, {
            status = ret_status
        } }
        Session.send_msg(s, msg)
    end
    
    mysql_center.edit_profile(uid, edit_profile_req.unick, edit_profile_req.uface, edit_profile_req.usex, ret_handle)
    redis_center.edit_profile(uid, edit_profile_req.unick, edit_profile_req.uface, edit_profile_req.usex)
    --end
end

local edit_profile = {
    edit_profile = do_edit_profile
}

return edit_profile