---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 1.
--- DateTime: 2020/11/16 22:27
---

local game_config = require("game_config")
local moba_game_config = require("moba_game_config")
local mysql_conn = nil

local function mysql_connect_to_moba_game()
    local conf = game_config.game_mysql

    local cb = function(err, conn)
        if err then
            Logger.error(err)
            Scheduler.once(mysql_connect_to_moba_game, 5000)
            return
        end

        Logger.debug("connect to moba game db success!!!!")
        mysql_conn = conn
    end

    MySql.connect(conf.host, conf.port, conf.db_name, conf.uname, conf.upwd, cb)
end

mysql_connect_to_moba_game()

local function get_ugame_info(uid, ret_handler)
    if mysql_conn == nil then
        if ret_handler then
            ret_handler("mysql is not connected!", nil)
        end
        return
    end
    
    local sql = "select uid, uchip, uchip2, uchip3, uvip, uvip_endtime, udata1, udata2, udata3, uexp, ustatus from ugame where uid = %d limit 1";
    local sql_cmd = string.format(sql, uid)

    MySql.query(mysql_conn, sql_cmd, function(err, ret)
        if err then
            if ret_handler then
                ret_handler(err, nil)
            end
            return
        end

        --没有这条记录
        if ret == nil or #ret <= 0 then
            if ret_handler then
                ret_handler(nil, nil)
            end
            return
        end

        local result = ret[1]
        local uinfo = {
            uid = tonumber(result[1]),
            uchip = tonumber(result[2]),
            uchip2 = tonumber(result[3]),
            uchip3 = tonumber(result[4]),
            uvip = tonumber(result[5]),
            uvip_endtime = tonumber(result[6]),
            udata1 = tonumber(result[7]),
            udata2 = tonumber(result[8]),
            udata3 = tonumber(result[9]),
            uexp = tonumber(result[10]),
            ustatus = tonumber(result[11]),
        }
        print(uinfo.uid, uinfo.uchip, uinfo.uvip, uinfo.uexp)
        if ret_handler then
            ret_handler(nil, uinfo)
        end
    end)
end

local function insert_ugame_info(uid, ret_handler)
    if mysql_conn == nil then
        if ret_handler then
            ret_handler("mysql is not connected!", nil)
        end
        return
    end

    local sql = "insert into ugame(`uid`, `uchip`, `uvip`, `uexp`)values(%d, %d, %d, %d)"
    local sql_cmd = string.format(sql, uid, moba_game_config.ugame.uchip, moba_game_config.ugame.uvip, moba_game_config.ugame.uexp)

    MySql.query(mysql_conn, sql_cmd, function(err, ret)
        if ret_handler then
            ret_handler(err, nil)
        end
    end)
end

local mysql_auth_center = {
    get_ugame_info = get_ugame_info,
    insert_ugame_info = insert_ugame_info,
}

return mysql_auth_center