---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 1.
--- DateTime: 2020/9/20 14:41
---
local Stype = require("Stype")

local remove_servers = {}

--注册我们的服务所部署的IP地址和端口
remove_servers[Stype.Auth] = {
    stype = Stype.Auth,
    ip = "127.0.0.1",
    port = 8000,
    desic = "Auth server",
}

remove_servers[Stype.System] = {
    stype = Stype.System,
    ip = "127.0.0.1",
    port = 8001,
    desci = "System server",
}


--配置
local game_config = {
    gateway_tcp_ip = "127.0.0.1",
    gateway_tcp_port = 6080,

    gateway_ws_ip = "127.0.0.1",
    gateway_ws_port = 6081,

    servers = remove_servers,

    auth_mysql = {
        host = "127.0.0.1",
        port = 3306,
        db_name = "auth_center",
        uname = "root",
        upwd = "123456",
    },

    game_mysql = {
        host = "127.0.0.1",
        port = 3306,
        db_name = "moba_game",
        uname = "root",
        upwd = "123456",
    },

    center_redis = {
        host = "127.0.0.1", --redis所在的host
        port = 6379, --redis 端口
        db_index = 1, --数据1
    },
    
    redis_game = {
        host = "127.0.0.1",
        port = 6379,
        db_index = 2,
    }
}

return game_config