---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 1.
--- DateTime: 2020/11/15 23:23
---

local moba_game_config = {
    ugame = {
        uchip = 2000,
        uvip = 0,
        uexp = 0,
    },
    
    login_bonues = {100, 200, 300, 400, 500}
}

return moba_game_config