---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 1.
--- DateTime: 2020/10/17 15:48
---

local Respones = {
    OK = 1,
    SystemErr = -100,
    UserIsFreeze = -101,
    UserIsNotGuest = -102,
    InvalidParams = -103,
    UnameIsExist = -104,
    UnameOrUpwdError = -105,
}

return Respones