---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 1.
--- DateTime: 2020/9/20 14:39
---服务器类型
---

local Stype = {
    Auth = 1, --用户服务
    System = 2, --系统服务
    Logic = 3, --逻辑服务
}

return Stype