---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 1.
--- DateTime: 2020/11/23 23:33
---

local Stype = require("Stype")
local Cmd = require("Cmd")
local Respones = require("Respones")
local mysql_game = require("database/mysql_game")
local redis_game = require("database/redis_game")
local player = require("logic_server/player")

-- uid --->player
local logic_server_players = {}
local online_player_num = 0 --在线人数

local function send_status(s, stype, ctype, uid, status)
    local msg = { stype, ctype, uid, {
        status = status
    } }
    Session.send_msg(s, msg)
end

local function login_logic(s, req)
    local uid = req[3]
    local p = logic_server_players[uid]
    --玩家对象已经在队列中, 更新一下session就可以了
    if p then
        p:set_session(s)
        Logger.error("if uid: " .. uid, "online member: " .. online_player_num)
        send_status(s, Stype.Logic, Cmd.eLoginLogicRes, uid, Respones.OK)
        return
    end

    p = player:new()
    p:init(uid, s, function(status)
        if status == Respones.OK then
            logic_server_players[uid] = p
            online_player_num = online_player_num + 1
            Logger.error("else uid: " .. uid, "online member: " .. online_player_num)
        end
        send_status(s, Stype.Logic, Cmd.eLoginLogicRes, uid, status)
    end)
end

--玩家离开了
local function on_player_disconnect(s, req)
    local uid = req[3]
    
    --游戏中的玩家我们后续考虑
    --end

    --玩家断线离开中
    if logic_server_players[uid] then
        logic_server_players[uid] = nil
        online_player_num = online_player_num - 1
    end
    --end
    Logger.error("on_player_disconnect", online_player_num)
end

--网关断线
local function on_gateway_disconnect(s)
    for i, v in pairs(logic_server_players) do
        v:set_session(nil)
    end
end

--网关连接
local function on_gateway_connect(s)
    print("on_gateway_connect")
    for i, v in pairs(logic_server_players) do
        v:set_session(s)
    end
end

local game_mgr = {
    login_logic = login_logic,
    on_player_disconnect = on_player_disconnect,
    on_gateway_disconnect = on_gateway_disconnect,
    on_gateway_connect = on_gateway_connect,
}

return game_mgr