---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 1.
--- DateTime: 2020/11/23 23:08
---
Logger.init("logger/logic_server/", "logic_server", true, false)

-- 初始化协议模块
local proto_type = {
    PROTO_JSON = 0,
    PROTO_BUF = 1,
}

ProtoMan.init(proto_type.PROTO_BUF)
if ProtoMan.proto_type() == proto_type.PROTO_BUF then
    local cmd_name_map = require("cmd_name_map")
    if cmd_name_map then
        ProtoMan.register_protobuf_cmd_map(cmd_name_map)
    end
end
--end

--开启网络服务
local game_config = require("game_config")
local Stype = require("Stype")
local servers = game_config.servers
print("Logic Server Start at " .. servers[Stype.Logic].port)
Netbus.tcp_listen(servers[Stype.Logic].port)
Netbus.udp_listen(8800);
--end

local logic_server = require("logic_server/logic_service")
local ret = Service.register_service(Stype.Logic, logic_server)
if ret then
    print("register Logic service:[" .. Stype.Logic .. "] success!!!")
else
    Logger.error("register Logic service:[" .. Stype.Logic .. "] failed!!!")
end