---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 1.
--- DateTime: 2020/11/23 23:38
---
local Stype = require("Stype")
local Cmd = require("Cmd")
local Respones = require("Respones")
local mysql_game = require("database/mysql_game")
local redis_game = require("database/redis_game")

local player = {}
function player:new(instant)
    if not instant then
        instant = {}
    end

    setmetatable(instant, { __index = self })
    return instant
end

function player:init(uid, s, ret_handler)
    self:set_session(s)
    self.v_uid = uid

    --数据库里面读取玩家的基本信息
    mysql_game.get_ugame_info(uid, function(err, ugame_info)
        if err then
            ret_handler(Respones.SystemErr)
        else
            self.v_ugame_info = ugame_info
            ret_handler(Respones.OK)
        end
    end)
    --end

    --。。。其他信息后面再读
    --end
end

function player:set_session(session)
    self.v_session = session
    local uid = Session.get_uid(session)
    local utag = Session.get_utag(session)
    local addr = Session.get_address(session)
    local is_client = Session.asclient(session)
    print(uid, utag, addr, is_client)
end

return player