---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 1.
--- DateTime: 2020/12/4 17:39
---房间状态
---
local State = {
    InView = 1, --集结玩家
    Ready = 2, --玩家集结完毕
    Start = 3, --玩家都准备好
    Playing = 4, --在游戏中
    CheckOut = 5, --游戏结算
}

return State